{
 "title": "App Voting",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Resumo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Voting status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "votes_total", "legendFormat": "{{vote_type}}" }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"backend|frontend:3000|worker:3000\"}[12h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Response duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=~\"backend|frontend:3000|worker:3000\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Active sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) !=0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Web Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Backend request total ",
   "type": "timeseries",
   "description": "Request total agrupadas de 1 em 1 minuto",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total[1m])) by (status, method)",
     "legendFormat": "{{ method }} - {{status}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requisições por segundo",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "description": "Errors per second",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[30s]))",
     "legendFormat": "{{ method }} - {{status}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Unit Usage (Milicores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",name=~\"worker|redis|database|backend|frontend\"}[1m]))by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{image!=\"\", name=~\"worker|redis|database|backend|frontend\"}[1m])) by (name)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Network In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\", name=~\"backend|frontend|worker\"}[1m])) ",
     "legendFormat": "{{ name }} In"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\", name=~\"backend|frontend|worker\"}[1m]))",
     "legendFormat": "{{ name }} Out"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "DB Transactions commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit[5m]) > 0",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "DB Transactions rollback",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_rollback[5m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "DB Insert data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(pg_stat_database_tup_inserted[1m])) by (datname)",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "DB Lock table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pg_locks_count!= 0", "legendFormat": "{{ datname }}" }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 34 },
   "targets": [
    { "expr": "sum (redis_db_keys) by (db)", "legendFormat": "Commands" }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total[1m]))",
     "legendFormat": "Commands"
    }
   ]
  }
 ]
}