# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

name: observability-learning
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

cloud.id: "brunavieira:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyRiYzY3M2RmNDJhNTg0NmNmOWVkZGFmM2QwNmMzZmNkMCQ5ZWNjMDQyYzQ2NDc0OTEzOTk3N2Y1NmQ2OTc4ZDEyZg=="
cloud.auth: "elastic:t3sSEvd0w9s3V13gPNcHb43s"

output.elasticsearch:
  pipeline: "pipeline-adatech"

logging.level: debug
logging.json: true
logging.selectors: ["*"]